# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('comment_type', models.CharField(choices=[('Dev', 'Dev'), ('User', 'User')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature')], max_length=10)),
                ('subject', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('priority', models.CharField(choices=[('Minor', 'Minor'), ('Normal', 'Normal'), ('High', 'High'), ('Critical', 'Critical')], default='Minor', max_length=10)),
                ('status', models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Reject', 'Reject'), ('Active', 'Active'), ('Complete', 'Complete')], default='New', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('done_date', models.DateTimeField()),
                ('up_vote', models.IntegerField(default=0)),
                ('accept', models.BinaryField(default=0)),
                ('upload_files', models.FileField(upload_to='upload_files')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket'),
        ),
    ]
