# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='done_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='due_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='upload_files',
            field=models.FileField(blank=True, upload_to='upload_files'),
        ),
    ]
